config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get       'login'   =>  'sessions#new'
  post      'login'   =>  'sessions#create'
  delete    'logout'  =>  'sessions#destroy'

  resources :users
  resources :albums

end

app/models/album.rb
class Album < ActiveRecord::Base
	validates :name, presence: true
	validates :artist, presence: true

	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 } 

	has_secure_password

	has_and_belongs_to_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action { logged_in_user }

	def index
		@albums = current_user.albums		
	end

	def create
		@album = Album.new(album_params)
	    if @album.save
	    	current_user.albums.push(@album)
		    flash[:success] = "Album added!"
			redirect_to albums_path
	    else
	    	render 'new'
	    end
	end

	def new
		@album = current_user.albums.build
	end

	# def edit
		
	# end

	# def show
		
	# end

	# def update
		
	# end

	# def destroy

	# end

	private

		def album_params
			params.require(:album).permit(:name, :artist)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
  	redirect_to root_path, notice: "Invalid address, please log in" unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create  	
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    	log_in(user)
    	redirect_to albums_path
	else
  		@invalid_credentials = "Invalid credentials"
		render 'new'		
  	end  	
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def show
		logged_in_user
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in(@user)
			redirect_to albums_path	
		else
			render 'new'
		end		
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def current_user=(user)
		@current_user = user
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album.html.erb
<li><strong><%= album.name %></strong> - <%= album.artist %></li>

app/views/albums/index.html.erb
<%= link_to "Add a new album", new_album_path %>
<ol>
  <%= render @albums %>
</ol>

app/views/albums/new.html.erb
<h1>Add a new album</h1>
<%= form_for(@album) do |f| %>	
	<div class="form-group">
		<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :artist %>
    	<%= f.text_field :artist, class: "form-control" %>		
	</div>	
	
	<%= f.submit "Add", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">        
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Albums Manager", root_path, class: "navbar-brand" %>            
        </div>
        <% if logged_in? %>        
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Albums", albums_path %></li>
                    <li><%= link_to "Profile", user_path(current_user) %></li>                    
                </ul>
            
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "Log out", logout_path, method: :delete %>                        
                    </li>
                </ul>            
            </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>AlbumsManager</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
        <div class="row">
            <div class="col-lg-12">

	            <% flash.each do |key, value| %>
			        <p class="flash-alert bg-danger alert-<%= key %> flash-margin"><%= value %></p>
			    <% end %>

				<%= yield %>

				<%= debug(params) if Rails.env.development? %>

			</div>
        </div>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="form-group">
		<%= f.label :name %>
    	<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :email %>
    	<%= f.email_field :email, class: "form-control" %>		
	</div>
	<div class="form-group">
		<%= f.label :password %>
    	<%= f.password_field :password, class: "form-control", placeholder: "Enter a password at least 6 characters long" %>
	</div>
	<div class="form-group">
		<%= f.label :password_confirmation %>
    	<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Repeat your password" %>
	</div>
	
	<%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<h2/><%= @user.name %></h2>
<p> <%= @user.email %></p>